import 'package:stock_n_grill_customer/core/const/svg_constants.dart';
import 'package:stock_n_grill_customer/model/data/category_model.dart';
import 'package:stock_n_grill_customer/model/data/iteam_model.dart';

class Dummy {
 static List<AddOn> ingredients_list = [
    AddOn('Salt', 0),
    AddOn('Sugar', 0),
    AddOn('Lemon', 1.02),
  ];
  static List<CategoryModel> categories = [
    CategoryModel(
      image: SvgConstants.snack,
      titile: 'Snacks',
      iteams: dataaaaa.where((e) => e.category == 'Snack').toList(),
      ingredients: [AddOn('Salt', 0), AddOn('Sugar', 0), AddOn('Lemon', 1.02)],
    ),
    CategoryModel(
      image: SvgConstants.meals,
      titile: 'Meal',
      iteams: dataaaaa.where((e) => e.category == 'meal').toList(),
      ingredients: [AddOn('Salt', 0), AddOn('Sugar', 0), AddOn('Lemon', 1.02)],
    ),
    CategoryModel(
      image: SvgConstants.vegan,
      titile: 'Vegan',
      iteams: dataaaaa.where((e) => e.category == 'vegan').toList(),
      ingredients: [AddOn('Salt', 0), AddOn('Sugar', 0), AddOn('Lemon', 1.02)],
    ),
    CategoryModel(
      image: SvgConstants.desserts,
      titile: 'Dessert',
      iteams: dataaaaa.where((e) => e.category == 'dessert').toList(),
      ingredients: [AddOn('Salt', 0), AddOn('Sugar', 0), AddOn('Lemon', 1.02)],
    ),
    CategoryModel(
      image: SvgConstants.drinks,
      titile: 'Drinks',
      iteams: dataaaaa.where((e) => e.category == 'drinks').toList(),
      ingredients: [AddOn('Salt', 0), AddOn('Sugar', 0), AddOn('Lemon', 1.02)],
    ),
  ];

  static List<IteamModel> dataaaaa = [
    IteamModel(
      category: 'dessert',
      titile: 'Chocolate Cake',
      rating: 3.9,
      fav: false,
      image: 'https://example.com/image2.jpg',
      price: 52.67,
      discrption: 'Healthy choice',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Chocolate Cake',
      rating: 3.6,
      fav: true,
      image: 'https://example.com/image20.jpg',
      price: 86.54,
      discrption: 'Rich in flavor',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Chocolate Cake',
      rating: 3.6,
      fav: true,
      image: 'https://example.com/image15.jpg',
      price: 65.91,
      discrption: 'Refreshing treat',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Grilled Sandwich',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image10.jpg',
      price: 16.45,
      discrption: 'Best seller',
      video: 'https://example.com/video3.mp4',
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Tofu Salad',
      rating: 3.1,
      fav: true,
      image: 'https://example.com/image13.jpg',
      price: 17.88,
      discrption: 'Healthy choice',
      video: null,
    ),

    // Additional 96 items
    IteamModel(
      category: 'dessert',
      titile: 'Vanilla Ice Cream',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image21.jpg',
      price: 12.99,
      discrption: 'Creamy and delicious',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Apple Pie',
      rating: 4.5,
      fav: false,
      image: 'https://example.com/image22.jpg',
      price: 35.50,
      discrption: 'Traditional favorite',
      video: 'https://example.com/video4.mp4',
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Strawberry Cheesecake',
      rating: 4.7,
      fav: true,
      image: 'https://example.com/image23.jpg',
      price: 45.75,
      discrption: 'Rich and creamy',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Tiramisu',
      rating: 4.6,
      fav: true,
      image: 'https://example.com/image24.jpg',
      price: 38.90,
      discrption: 'Italian classic',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Chocolate Brownie',
      rating: 4.3,
      fav: false,
      image: 'https://example.com/image25.jpg',
      price: 25.60,
      discrption: 'Fudgy delight',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Chicken Burger',
      rating: 4.1,
      fav: true,
      image: 'https://example.com/image26.jpg',
      price: 28.75,
      discrption: 'Juicy and tender',
      video: 'https://example.com/video5.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'Beef Steak',
      rating: 4.8,
      fav: true,
      image: 'https://example.com/image27.jpg',
      price: 89.99,
      discrption: 'Premium quality',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Fish and Chips',
      rating: 4.0,
      fav: false,
      image: 'https://example.com/image28.jpg',
      price: 32.45,
      discrption: 'British classic',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Pasta Carbonara',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image29.jpg',
      price: 26.80,
      discrption: 'Creamy Italian',
      video: 'https://example.com/video6.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'Chicken Caesar Salad',
      rating: 3.8,
      fav: false,
      image: 'https://example.com/image30.jpg',
      price: 22.95,
      discrption: 'Fresh and healthy',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Fresh Orange Juice',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image31.jpg',
      price: 8.50,
      discrption: 'Vitamin C rich',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Cappuccino',
      rating: 4.5,
      fav: true,
      image: 'https://example.com/image32.jpg',
      price: 12.75,
      discrption: 'Perfect morning start',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Green Smoothie',
      rating: 3.9,
      fav: false,
      image: 'https://example.com/image33.jpg',
      price: 15.60,
      discrption: 'Healthy and nutritious',
      video: 'https://example.com/video7.mp4',
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Iced Tea',
      rating: 3.7,
      fav: true,
      image: 'https://example.com/image34.jpg',
      price: 6.99,
      discrption: 'Refreshing beverage',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Mango Lassi',
      rating: 4.3,
      fav: false,
      image: 'https://example.com/image35.jpg',
      price: 11.25,
      discrption: 'Traditional Indian drink',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Quinoa Bowl',
      rating: 4.1,
      fav: true,
      image: 'https://example.com/image36.jpg',
      price: 24.50,
      discrption: 'Protein packed',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Avocado Toast',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image37.jpg',
      price: 18.90,
      discrption: 'Instagram worthy',
      video: 'https://example.com/video8.mp4',
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Lentil Curry',
      rating: 4.2,
      fav: false,
      image: 'https://example.com/image38.jpg',
      price: 21.75,
      discrption: 'Spicy and flavorful',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Vegetable Stir Fry',
      rating: 3.8,
      fav: true,
      image: 'https://example.com/image39.jpg',
      price: 19.60,
      discrption: 'Quick and healthy',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Coconut Rice',
      rating: 4.4,
      fav: false,
      image: 'https://example.com/image40.jpg',
      price: 16.25,
      discrption: 'Aromatic and tasty',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Lobster Thermidor',
      rating: 4.9,
      fav: true,
      image: 'https://example.com/image41.jpg',
      price: 125.99,
      discrption: 'Luxury dining',
      video: 'https://example.com/video9.mp4',
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Wagyu Beef',
      rating: 4.8,
      fav: true,
      image: 'https://example.com/image42.jpg',
      price: 189.50,
      discrption: 'World class quality',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Truffle Pasta',
      rating: 4.7,
      fav: false,
      image: 'https://example.com/image43.jpg',
      price: 95.75,
      discrption: 'Gourmet experience',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Caviar Platter',
      rating: 4.6,
      fav: true,
      image: 'https://example.com/image44.jpg',
      price: 299.99,
      discrption: 'Ultimate luxury',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Gold Leaf Dessert',
      rating: 4.2,
      fav: false,
      image: 'https://example.com/image45.jpg',
      price: 150.00,
      discrption: 'Edible gold experience',
      video: 'https://example.com/video10.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'Turkey Club Sandwich',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image46.jpg',
      price: 24.95,
      discrption: 'Triple decker delight',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Chicken Tikka Masala',
      rating: 4.5,
      fav: true,
      image: 'https://example.com/image47.jpg',
      price: 29.80,
      discrption: 'Indian favorite',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Sushi Platter',
      rating: 4.6,
      fav: false,
      image: 'https://example.com/image48.jpg',
      price: 65.40,
      discrption: 'Fresh and authentic',
      video: 'https://example.com/video11.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'BBQ Ribs',
      rating: 4.3,
      fav: true,
      image: 'https://example.com/image49.jpg',
      price: 42.75,
      discrption: 'Fall off the bone',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Margherita Pizza',
      rating: 4.1,
      fav: false,
      image: 'https://example.com/image50.jpg',
      price: 22.60,
      discrption: 'Classic Italian',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Crème Brûlée',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image51.jpg',
      price: 28.90,
      discrption: 'French elegance',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Red Velvet Cake',
      rating: 4.2,
      fav: false,
      image: 'https://example.com/image52.jpg',
      price: 41.25,
      discrption: 'Southern classic',
      video: 'https://example.com/video12.mp4',
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Chocolate Mousse',
      rating: 4.5,
      fav: true,
      image: 'https://example.com/image53.jpg',
      price: 32.80,
      discrption: 'Light and airy',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Lemon Tart',
      rating: 4.0,
      fav: false,
      image: 'https://example.com/image54.jpg',
      price: 26.45,
      discrption: 'Tangy and sweet',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Panna Cotta',
      rating: 4.3,
      fav: true,
      image: 'https://example.com/image55.jpg',
      price: 24.70,
      discrption: 'Silky smooth',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Espresso',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image56.jpg',
      price: 8.95,
      discrption: 'Strong and bold',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Berry Smoothie',
      rating: 4.1,
      fav: false,
      image: 'https://example.com/image57.jpg',
      price: 13.50,
      discrption: 'Antioxidant rich',
      video: 'https://example.com/video13.mp4',
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Hot Chocolate',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image58.jpg',
      price: 10.75,
      discrption: 'Warm and comforting',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Lemonade',
      rating: 3.9,
      fav: false,
      image: 'https://example.com/image59.jpg',
      price: 7.25,
      discrption: 'Fresh and zesty',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Matcha Latte',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image60.jpg',
      price: 14.90,
      discrption: 'Zen in a cup',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Buddha Bowl',
      rating: 4.3,
      fav: true,
      image: 'https://example.com/image61.jpg',
      price: 26.85,
      discrption: 'Mindful eating',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Chickpea Curry',
      rating: 4.1,
      fav: false,
      image: 'https://example.com/image62.jpg',
      price: 20.50,
      discrption: 'Protein powerhouse',
      video: 'https://example.com/video14.mp4',
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Raw Zucchini Noodles',
      rating: 3.7,
      fav: true,
      image: 'https://example.com/image63.jpg',
      price: 18.25,
      discrption: 'Low carb alternative',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Cashew Cheese',
      rating: 3.9,
      fav: false,
      image: 'https://example.com/image64.jpg',
      price: 22.40,
      discrption: 'Dairy free delight',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Stuffed Bell Peppers',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image65.jpg',
      price: 25.60,
      discrption: 'Colorful and nutritious',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Lamb Chops',
      rating: 4.6,
      fav: true,
      image: 'https://example.com/image66.jpg',
      price: 58.90,
      discrption: 'Tender and flavorful',
      video: 'https://example.com/video15.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'Seafood Paella',
      rating: 4.5,
      fav: false,
      image: 'https://example.com/image67.jpg',
      price: 45.75,
      discrption: 'Spanish tradition',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Duck Confit',
      rating: 4.7,
      fav: true,
      image: 'https://example.com/image68.jpg',
      price: 52.30,
      discrption: 'French masterpiece',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Pork Belly',
      rating: 4.4,
      fav: false,
      image: 'https://example.com/image69.jpg',
      price: 38.65,
      discrption: 'Crispy and succulent',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Ramen Bowl',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image70.jpg',
      price: 24.95,
      discrption: 'Japanese comfort food',
      video: 'https://example.com/video16.mp4',
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Kobe Beef Steak',
      rating: 4.9,
      fav: true,
      image: 'https://example.com/image71.jpg',
      price: 350.00,
      discrption: 'Once in a lifetime',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Oyster Rockefeller',
      rating: 4.5,
      fav: false,
      image: 'https://example.com/image72.jpg',
      price: 85.50,
      discrption: 'Sophisticated starter',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Foie Gras',
      rating: 4.6,
      fav: true,
      image: 'https://example.com/image73.jpg',
      price: 145.75,
      discrption: 'French delicacy',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Molecular Gastronomy',
      rating: 4.3,
      fav: false,
      image: 'https://example.com/image74.jpg',
      price: 195.99,
      discrption: 'Science meets cuisine',
      video: 'https://example.com/video17.mp4',
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Abalone',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image75.jpg',
      price: 175.25,
      discrption: 'Ocean treasure',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Macarons',
      rating: 4.1,
      fav: false,
      image: 'https://example.com/image76.jpg',
      price: 18.50,
      discrption: 'Parisian perfection',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Banoffee Pie',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image77.jpg',
      price: 29.75,
      discrption: 'British favorite',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Gelato',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image78.jpg',
      price: 15.80,
      discrption: 'Italian artistry',
      video: 'https://example.com/video18.mp4',
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Pavlova',
      rating: 4.2,
      fav: false,
      image: 'https://example.com/image79.jpg',
      price: 33.90,
      discrption: 'Light meringue base',
      video: null,
    ),
    IteamModel(
      category: 'dessert',
      titile: 'Profiteroles',
      rating: 4.3,
      fav: true,
      image: 'https://example.com/image80.jpg',
      price: 26.65,
      discrption: 'Choux pastry delight',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Craft Beer',
      rating: 4.0,
      fav: false,
      image: 'https://example.com/image81.jpg',
      price: 12.50,
      discrption: 'Artisanal brewing',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Wine Selection',
      rating: 4.5,
      fav: true,
      image: 'https://example.com/image82.jpg',
      price: 45.00,
      discrption: 'Curated collection',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Kombucha',
      rating: 3.8,
      fav: false,
      image: 'https://example.com/image83.jpg',
      price: 9.75,
      discrption: 'Probiotic drink',
      video: 'https://example.com/video19.mp4',
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Coconut Water',
      rating: 3.6,
      fav: true,
      image: 'https://example.com/image84.jpg',
      price: 6.25,
      discrption: 'Natural hydration',
      video: null,
    ),
    IteamModel(
      category: 'drinks',
      titile: 'Energy Drink',
      rating: 3.4,
      fav: false,
      image: 'https://example.com/image85.jpg',
      price: 8.99,
      discrption: 'Power boost',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Jackfruit Tacos',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image86.jpg',
      price: 19.95,
      discrption: 'Meat alternative',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Almond Milk Yogurt',
      rating: 3.7,
      fav: false,
      image: 'https://example.com/image87.jpg',
      price: 12.40,
      discrption: 'Dairy free option',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Seitan Steak',
      rating: 3.9,
      fav: true,
      image: 'https://example.com/image88.jpg',
      price: 23.85,
      discrption: 'Wheat protein based',
      video: 'https://example.com/video20.mp4',
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Mushroom Risotto',
      rating: 4.3,
      fav: false,
      image: 'https://example.com/image89.jpg',
      price: 28.70,
      discrption: 'Earthy and creamy',
      video: null,
    ),
    IteamModel(
      category: 'vegan',
      titile: 'Tempeh Burger',
      rating: 3.8,
      fav: true,
      image: 'https://example.com/image90.jpg',
      price: 21.50,
      discrption: 'Fermented goodness',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Fish Tacos',
      rating: 4.1,
      fav: false,
      image: 'https://example.com/image91.jpg',
      price: 26.85,
      discrption: 'Coastal favorite',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Shepherd\'s Pie',
      rating: 4.0,
      fav: true,
      image: 'https://example.com/image92.jpg',
      price: 22.95,
      discrption: 'Comfort food classic',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Pad Thai',
      rating: 4.4,
      fav: true,
      image: 'https://example.com/image93.jpg',
      price: 24.60,
      discrption: 'Thai street food',
      video: 'https://example.com/video21.mp4',
    ),
    IteamModel(
      category: 'meal',
      titile: 'Chicken Quesadilla',
      rating: 3.9,
      fav: false,
      image: 'https://example.com/image94.jpg',
      price: 19.75,
      discrption: 'Mexican favorite',
      video: null,
    ),
    IteamModel(
      category: 'meal',
      titile: 'Beef Burrito',
      rating: 4.2,
      fav: true,
      image: 'https://example.com/image95.jpg',
      price: 21.30,
      discrption: 'Wrapped satisfaction',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Tasting Menu',
      rating: 4.8,
      fav: true,
      image: 'https://example.com/image96.jpg',
      price: 295.00,
      discrption: 'Chef\'s selection',
      video: null,
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Vintage Champagne',
      rating: 4.7,
      fav: false,
      image: 'https://example.com/image97.jpg',
      price: 485.99,
      discrption: 'Celebration worthy',
      video: 'https://example.com/video22.mp4',
    ),
    IteamModel(
      category: 'Snack',
      titile: 'Aged Whiskey',
      rating: 4.6,
      fav: true,
      image: 'https://example.com/image98.jpg',
      price: 275.50,
      discrption: '25 year aged',
      video: null,
    ),
  ];
}
