// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdarKnQhju-TGI4UB6M7JoVIXoShSOhY',
    appId: '1:11131251179:web:f1460d63b4c09ee0fdd1ae',
    messagingSenderId: '11131251179',
    projectId: 'stock-n-grill',
    authDomain: 'stock-n-grill.firebaseapp.com',
    storageBucket: 'stock-n-grill.firebasestorage.app',
    measurementId: 'G-6797TRRW1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_aPoeiwv8KTjVcwIuQl7-71FQ03em5Pk',
    appId: '1:11131251179:android:464e18492a5ba8a3fdd1ae',
    messagingSenderId: '11131251179',
    projectId: 'stock-n-grill',
    storageBucket: 'stock-n-grill.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArK0gv_570GCJ5uX7_jBjPM5mEwgstW5A',
    appId: '1:11131251179:ios:d49911f4ae6bab27fdd1ae',
    messagingSenderId: '11131251179',
    projectId: 'stock-n-grill',
    storageBucket: 'stock-n-grill.firebasestorage.app',
    iosBundleId: 'com.example.stockNGrillCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArK0gv_570GCJ5uX7_jBjPM5mEwgstW5A',
    appId: '1:11131251179:ios:d49911f4ae6bab27fdd1ae',
    messagingSenderId: '11131251179',
    projectId: 'stock-n-grill',
    storageBucket: 'stock-n-grill.firebasestorage.app',
    iosBundleId: 'com.example.stockNGrillCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZdarKnQhju-TGI4UB6M7JoVIXoShSOhY',
    appId: '1:11131251179:web:21648eb356348b56fdd1ae',
    messagingSenderId: '11131251179',
    projectId: 'stock-n-grill',
    authDomain: 'stock-n-grill.firebaseapp.com',
    storageBucket: 'stock-n-grill.firebasestorage.app',
    measurementId: 'G-1R3ETX6X8Z',
  );

}
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );